name: Ruby Gem

on:
  create:
    ref_type: tag

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish
    strategy:
      matrix:
        ruby:
          - '2.7.3'
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.7.3
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7.3
      - run: bundle install

      - name: Publish to RubyGems
        run: |
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"